package project;

import java.sql.SQLException;

import dataStructures.*;

public class Input extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	private Integer numberOfCars;
    private Double frequency;
    private String nonFormatedFromZones;
    private String nonFormatedToZones;
    private Zones fromZones; 
    private Zones toZones;    /** Creates new form NewJFrame */
    public Input() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabelNumberCars = new javax.swing.JLabel();
        jTextFieldNumberCars = new javax.swing.JTextField();
        jLabelFromZones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaFromZones = new javax.swing.JTextArea();
        jLabelToZones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaToZones = new javax.swing.JTextArea();
        jButtonSubmit = new javax.swing.JButton();
        jLabelFrequency = new javax.swing.JLabel();
        jTextFieldFrequency = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaSubmit = new javax.swing.JTextArea();
        jButtonConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNumberCars.setText("Number of cars:");

        jTextFieldNumberCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumberCarsActionPerformed(evt);
            }
        });

        jLabelFromZones.setText("From zones: [center coordinate (Lat Lng); radius (meters)]");

        jTextAreaFromZones.setColumns(20);
        jTextAreaFromZones.setRows(5);
        jScrollPane1.setViewportView(jTextAreaFromZones);

        jLabelToZones.setText("To zones: [center coordinate (Lat Lng); radius (meters)]");

        jTextAreaToZones.setColumns(20);
        jTextAreaToZones.setRows(5);
        jScrollPane2.setViewportView(jTextAreaToZones);

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubmitMouseClicked(evt);
            }
        });

        jLabelFrequency.setText("Frequency (seconds)");

        jTextFieldFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFrequencyActionPerformed(evt);
            }
        });

        jTextAreaSubmit.setColumns(20);
        jTextAreaSubmit.setEditable(false);
        jTextAreaSubmit.setRows(5);
        jScrollPane3.setViewportView(jTextAreaSubmit);

        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmMouseClicked(evt);
            }
        });
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jScrollPane3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelFromZones)
                                .addComponent(jLabelToZones)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelNumberCars)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldNumberCars, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(23, 23, 23)
                                            .addComponent(jLabelFrequency)))
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumberCars)
                    .addComponent(jTextFieldNumberCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFrequency)
                    .addComponent(jTextFieldFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFromZones)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelToZones))
                .addGap(18, 18, 18)
                .addComponent(jButtonSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButtonConfirm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jTextFieldNumberCarsActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jTextFieldFrequencyActionPerformed(java.awt.event.ActionEvent evt) {
       
    }

    private void jButtonSubmitMouseClicked(java.awt.event.MouseEvent evt) {
        jTextAreaSubmit.setText("");
        String insert = jTextFieldNumberCars.getText()+ "#" +
                jTextFieldFrequency.getText()+ "#" +
                jTextAreaFromZones.getText()+ "#" +
                jTextAreaToZones.getText();
        if(insert.length() <= 3)
        	jTextAreaSubmit.setText("5#1#57.04711 9.91231 100#57.04704 9.91545 100");//jTextAreaSubmit.setText("5#1#57.043952 9.921952 100#57.047045 9.915451 100");       /* jTextAreaSubmit.setText("5#1#582319.51 6323951.61 100#717230.03 6182185.2 100"); */
        //57.04711033901427,9.912316530298757
        else    
        	jTextAreaSubmit.setText(insert);
    }

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {
       
    }

    private void jButtonConfirmMouseClicked(java.awt.event.MouseEvent evt) {
        this.fromZones = new Zones();
        this.toZones = new Zones();       
        
        String input[] = jTextAreaSubmit.getText().split("#");
        this.numberOfCars = Integer.parseInt(input[0]);
        this.frequency = Double.parseDouble(input[1]);
        this.nonFormatedFromZones = input[2];
        if(!input[3].isEmpty())
        	this.nonFormatedToZones = input[3];
        else 
        	this.nonFormatedToZones = "";
        
        String rawSplit[] = this.nonFormatedFromZones.split(":");
	    for(int i = 0; i < rawSplit.length; i++) {
		   this.fromZones.addZone( new Zone(rawSplit[i], "LatLon" ));
		     
        }
	    String colSplit[] = nonFormatedToZones.split(":");
	    for(int i = 0; i < colSplit.length; i++) {
		   this.toZones.addZone( new Zone(colSplit[i], "LatLon" )  );
        }
        

        this.setVisible(false);        
        UserInput userInput = new UserInput(this.numberOfCars, this.frequency, 100, this.fromZones, this.toZones);
        TrafficAlgorithm traffic = null;
		try {
			traffic = new TrafficAlgorithm(userInput);
		} catch (SQLException e) {
			e.printStackTrace();
		}
        traffic.run();
    }

    public void start(){
		java.awt.EventQueue.invokeLater(new Runnable() {
	        public void run() {
	            new Input().setVisible(true);
	        }
	    });
			    	    
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabelFrequency;
    private javax.swing.JLabel jLabelFromZones;
    private javax.swing.JLabel jLabelNumberCars;
    private javax.swing.JLabel jLabelToZones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaFromZones;
    private javax.swing.JTextArea jTextAreaSubmit;
    private javax.swing.JTextArea jTextAreaToZones;
    private javax.swing.JTextField jTextFieldFrequency;
    private javax.swing.JTextField jTextFieldNumberCars;
    // End of variables declaration

}
